# Tabla de constantes del juego

### PANTALLA ###

ANCHO = 720
ALTO = 480
CENTER = (ANCHO // 2, ALTO // 2)

FPS = 60

TIEMPO = 180 # En segundos

### PLANTA ###

SCALE_FOR_PLANT = 0.45

### STATS ###

SCALE_FOR_BOTTOM_WATER = 0.25
SCALE_FOR_WATER = 0.125

SCALE_FOR_POSTIT = 0.5

SCALE_FOR_TIME = 0.125

SCALE_FOR_SKIP = 0.25

SCALE_FOR_HUGE_TIME = 1

#                                                  MINIJUEGOS

MINIGAME_X = 600
MINIGAME_Y = 330

### MINIJUEGO AGUA ###

# Necesitaria los pixeles del sprite para esto
PERSON_ANCHO = 50
PERSON_ALTO = 50

PERSON_X = 200
PERSON_SPEED = 5
PERSON_JUMP = 18
PERSON_GRAVITY = 1

### TAP (MINOJUEGO AGUA)
TAP_X = 655

### MINIJUEGO SOIL ###
MIN_DISTANCE = 20
WORM_QUANTITY_MIN = 5
WORM_QUANTITY_MAX = 8

### MINIJUEGO TEMPERATURA ###
TEMP_BACKGROUND = (450,300)
SELECTOR_SPEED = 10
SELECTOR_X = CENTER[0]
SELECTOR_Y = CENTER[1]
SELECTOR_SURFACE = (20,20)
ERROR_Y = CENTER[1]